### ISSUE TITLE
Activating extension nortakales.vs-qalc failed due to an error 

### ISSUE THREAD

**Issue by Krysl** [nortakales/vs-code-qalc#34]
`VSCode 1.85.1`
`vs-qalc-0.1.14`
```
2023-12-18 06:20:03.663 [info] ExtensionService#_doActivateExtension nortakales.vs-qalc, startup: false, activationEvent: 'onStartupFinished'
2023-12-18 06:20:05.773 [error] Activating extension nortakales.vs-qalc failed due to an error:
2023-12-18 06:20:05.773 [error] Error: Cannot find module './test/tests'
Require stack:
- g:\extensions\vscode-extensions-dir\nortakales.vs-qalc-0.1.14\out\currency.js
- g:\extensions\vscode-extensions-dir\nortakales.vs-qalc-0.1.14\out\math.js
- g:\extensions\vscode-extensions-dir\nortakales.vs-qalc-0.1.14\out\document.js
- g:\extensions\vscode-extensions-dir\nortakales.vs-qalc-0.1.14\out\decorator.js
- g:\extensions\vscode-extensions-dir\nortakales.vs-qalc-0.1.14\out\extension.js
```

<details>
  <summary>Full log (Click to expand)</summary>

```
2023-12-18 06:20:03.663 [info] ExtensionService#_doActivateExtension nortakales.vs-qalc, startup: false, activationEvent: 'onStartupFinished'
2023-12-18 06:20:05.773 [error] Activating extension nortakales.vs-qalc failed due to an error:
2023-12-18 06:20:05.773 [error] Error: Cannot find module './test/tests'
Require stack:
- g:\extensions\vscode-extensions-dir\nortakales.vs-qalc-0.1.14\out\currency.js
- g:\extensions\vscode-extensions-dir\nortakales.vs-qalc-0.1.14\out\math.js
- g:\extensions\vscode-extensions-dir\nortakales.vs-qalc-0.1.14\out\document.js
- g:\extensions\vscode-extensions-dir\nortakales.vs-qalc-0.1.14\out\decorator.js
- g:\extensions\vscode-extensions-dir\nortakales.vs-qalc-0.1.14\out\extension.js
- d:\Program Files\VS Code\resources\app\out\vs\loader.js
- d:\Program Files\VS Code\resources\app\out\bootstrap-amd.js
- d:\Program Files\VS Code\resources\app\out\bootstrap-fork.js
- 
	at Module._resolveFilename (node:internal/modules/cjs/loader:1129:15)
	at s._resolveFilename (node:electron/js2c/utility_init:2:2786)
	at Module._load (node:internal/modules/cjs/loader:974:27)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at c._load (d:\Program Files\VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:171:5632)
	at n._load (d:\Program Files\VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:168:29551)
	at t._load (d:\Program Files\VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:133:35226)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at h (d:\Program Files\VS Code\resources\app\out\vs\loader.js:4:647)
	at Object.<anonymous> (g:\extensions\vscode-extensions-dir\nortakales.vs-qalc-0.1.14\out\currency.js:14:17)
	at o._compile (d:\Program Files\VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at c._load (d:\Program Files\VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:171:5632)
	at n._load (d:\Program Files\VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:168:29551)
	at t._load (d:\Program Files\VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:133:35226)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at h (d:\Program Files\VS Code\resources\app\out\vs\loader.js:4:647)
	at Object.<anonymous> (g:\extensions\vscode-extensions-dir\nortakales.vs-qalc-0.1.14\out\math.js:5:20)
	at o._compile (d:\Program Files\VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at c._load (d:\Program Files\VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:171:5632)
	at n._load (d:\Program Files\VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:168:29551)
	at t._load (d:\Program Files\VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:133:35226)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at h (d:\Program Files\VS Code\resources\app\out\vs\loader.js:4:647)
	at Object.<anonymous> (g:\extensions\vscode-extensions-dir\nortakales.vs-qalc-0.1.14\out\document.js:5:16)
	at o._compile (d:\Program Files\VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at c._load (d:\Program Files\VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:171:5632)
	at n._load (d:\Program Files\VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:168:29551)
	at t._load (d:\Program Files\VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:133:35226)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at h (d:\Program Files\VS Code\resources\app\out\vs\loader.js:4:647)
	at Object.<anonymous> (g:\extensions\vscode-extensions-dir\nortakales.vs-qalc-0.1.14\out\decorator.js:4:20)
	at o._compile (d:\Program Files\VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at c._load (d:\Program Files\VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:171:5632)
	at n._load (d:\Program Files\VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:168:29551)
	at t._load (d:\Program Files\VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:133:35226)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at h (d:\Program Files\VS Code\resources\app\out\vs\loader.js:4:647)
	at Object.<anonymous> (g:\extensions\vscode-extensions-dir\nortakales.vs-qalc-0.1.14\out\extension.js:5:21)
	at o._compile (d:\Program Files\VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
	at Module.load (node:internal/modules/cjs/loader:1171:32)
	at Module._load (node:internal/modules/cjs/loader:1012:12)
	at f._load (node:electron/js2c/asar_bundle:2:13377)
	at c._load (d:\Program Files\VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:171:5632)
	at n._load (d:\Program Files\VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:168:29551)
	at t._load (d:\Program Files\VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:133:35226)
	at Module.require (node:internal/modules/cjs/loader:1195:19)
	at require (node:internal/modules/cjs/helpers:110:18)
	at Function.i [as __$__nodeRequire] (d:\Program Files\VS Code\resources\app\out\vs\loader.js:5:98)
	at f.vb (d:\Program Files\VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:168:30730)
	at async Promise.all (index 0)
```

</details>

**Comment by nortakales** [comment]
Thanks for noticing this. This did not show up in testing! Fixed in `0.1.15`.
